### ISSUE TITLE
elemental2 Dom

### ISSUE THREAD

**Issue by lobmarib** [TDesjardins/gwt-ol3#111]
I've just updated to the last version of the wrapper and I found a new dependency on the gwt-ol3-client which is not being included in the artifact. Can't understand this approach. It's really needed?
On the previous version I added the gwt-ol3-client jar has dependency into my project and that's it. Quick and simple. (Yes my project doesn't use maven)

**Comment by TDesjardins** [comment]
@lobmarib Yes, there is a new dependency. I want to keep gwt-ol3 as simple as possible with less dependencies as possible. Elemental2 is needed for using DOM stuff and to keep gwt-ol3 prepared for the future. In release 4.0.0 this was introduced to support WFS format, especially to deal with XML-DOM elements, because the standard GWT-XML-API won't work with JSInterop or JSNI.

**Comment by ibaca** [comment]
You really should use some build tool 😞. Probably maven or gradle.

**Comment by lobmarib** [comment]
@TDesjardins ok. Was decided to keep the old version so.

@ibaca Unfortunately, not my call.

**Comment by TDesjardins** [comment]
@lobmarib You want to keep the old version? What are the pros of this decision? One more important dependency which you will anyway have sooner or later in your application ;-)

**Comment by lobmarib** [comment]
@TDesjardins Yes, we're going to keep up with the old version. For the moment the application is working fine with it and it seems there isn't much more to implement... 
I know that, but before that we need to take other decisions... if widgets disappear we'll be in a bigger trouble.

**Comment by TDesjardins** [comment]
I see. Good old widgets :-D
