### ISSUE TITLE
Renaming artifactId

### ISSUE THREAD

**Issue by peterza** [TDesjardins/gwt-ol3#50]
Is `gwt-ol3` the final stable artefactId of gwt-ol3 library?

**Comment by ibaca** [comment]
The final name is gwt-ol3. I hope is OK! 👌

**Comment by ibaca** [comment]
The name was changed from `gwt-ol3-client` to `gwt-ol3` because is "better" 😛, it is a bit annoying because updating from 2.8.0 to 2.9.0 will result in an "dependency not found" but, on the other hand, is a remainder of removing the old jitpack repository because this is the first release in maven central, so you no longer need to add any custom repository.

**Comment by TDesjardins** [comment]
Yes `gwt-ol3` is the better, stable and final artefactId and now available at maven central.
