### ISSUE TITLE
Using concrete classes instead of interfaces for Options

### ISSUE THREAD

**Issue by peterza** [TDesjardins/gwt-ol3#54]
@TDesjardins, is there a reason you used interfaces instead of concrete classes for Options?
Do you prefer using interfaces in conjunction with the OLFactory or  may I convert MapOptions ecc. to classes?

`public class MapOptions implements Options`

**Comment by TDesjardins** [comment]
Hello @peterza,

let me raise a counter question. What are the benefits when using classes for options? In most cases gwt-ol3 uses classes with native methods, so that you can use also constructors. With options this is not possible with JsInterop because the underlying JS-Object hasn't a constructor named like this class. Sure you could create it with a factory but when using the constructor, your code fails.

Regards

Tino

**Comment by peterza** [comment]
Ah, ok!

Thanks

Peter

**Comment by TDesjardins** [comment]
You are welcome.

**Comment by TDesjardins** [comment]
Hello @peterza,

i have an update for this issue. The use of classes works for options, if you use the global namespace and the object name 'Object'. After this modification you can also use the new operator. See commit https://github.com/TDesjardins/gwt-ol3/commit/f35e008c0a47337189dfe426780af47835f8916a

Regards

Tino
