### ISSUE TITLE
Drop oss-parent from pom

### ISSUE THREAD

**Issue by TDesjardins** [TDesjardins/gwt-ol3#85]
Remove oss-parent because of it's deprecation:
http://central.sonatype.org/pages/apache-maven.html#deprecated-oss-parent

@ibaca Do you see any problems for release goals when removing it?

**Comment by ibaca** [comment]
hehe yep, I need to apply this to rxgwt too... we will see if I detect any problem a apply/comment it here. If you want, just wait and when I apply it to my lib I just do the same here 👍.

**Comment by ibaca** [comment]
Now it is possible to deploy directly to maven central without the need of manually close and release using the oss.sonaype.org nexus web app. But, I have not used this strategy because it requires the plugin and because hehe the manual process adds some "safety" to the process, so forces you to review if the generated artifacts are the expected one or maybe just drop the release because you see something weird in the log. Not sure, you can try the new strategy just adding this and removing the staging distribution management entry.
```xml
<plugin>
  <groupId>org.sonatype.plugins</groupId>
  <artifactId>nexus-staging-maven-plugin</artifactId>
  <version>1.6.7</version>
  <extensions>true</extensions>
  <configuration>
     <serverId>ossrh</serverId>
     <nexusUrl>https://oss.sonatype.org/</nexusUrl>
     <autoReleaseAfterClose>true</autoReleaseAfterClose>
  </configuration>
</plugin>
```
More info here http://central.sonatype.org/pages/apache-maven.html

**Comment by TDesjardins** [comment]
Thanks, I will try it with the next release.
